inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.2
  NewCops: enable

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'gemfiles/*.gemfile'

Gemspec/RequireMFA:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false
