inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2
  NewCops: enable

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'gemfiles/*.gemfile'

Gemspec/RequireMFA:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false
