inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 6.1
  NewCops: enable

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'gemfiles/*.gemfile'

Gemspec/RequireMFA:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false
