inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.3
  TargetRailsVersion: 8.0
  NewCops: enable

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Gemspec/RequireMFA:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false
