sudo: false

language: ruby

cache: bundler

rvm:
  - 2.4.7
  - 2.5.6
  - 2.6.4

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4-2
  - gemfiles/Gemfile.rails-5-0
  - gemfiles/Gemfile.rails-5-1
  - gemfiles/Gemfile.rails-5-2

install:
  - bundle install

script:
  - bundle exec rspec spec/

matrix:
  fast_finish: true
