os: linux

dist: bionic

language: ruby

cache: bundler

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-5-2
  - gemfiles/Gemfile.rails-6-0

install:
  - bundle install

script:
  - bundle exec rspec spec/
  - bundle exec rake rubocop

jobs:
  fast_finish: true
