sudo: false

language: ruby

cache: bundler

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-5-2
  - gemfiles/Gemfile.rails-6-0

install:
  - bundle install

script:
  - bundle exec rspec spec/

matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/Gemfile.rails-6-0
      rvm: 2.4.9
