sudo: false

language: ruby

cache: bundler

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4-2
  - gemfiles/Gemfile.rails-5-0
  - gemfiles/Gemfile.rails-5-1

install:
  - bundle install

script:
  - bundle exec rspec spec/

matrix:
  fast_finish: true
  exclude:
